stages:
  - mavenbuild
  - maventest
  - mavendeploy
  - androidbuild
  - androidtest

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend/GlobeGatherer
    - mvn package
  artifacts:
    paths:
      - Backend/GlobeGatherer/target/*.jar

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend/GlobeGatherer
    - mvn test
  dependencies:
    - maven-build

auto-deploy:
  stage: mavendeploy
  tags:
    - springboot_tag
  script:
    - cd Backend/GlobeGatherer
    - sudo mv target/*.jar target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  dependencies:
    - maven-build

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew build

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew test
